<?php
add_action('acf/include_fields', function () {
 if (!function_exists('acf_add_local_field_group')) {
  return;
 }

 acf_add_local_field_group(array(
  'key' => 'group_658a3e6a1b0df',
  'title' => 'Banner Slider',
  'fields' => array(
   array(
    'key' => 'field_658a3e6a9625e',
    'label' => 'Slider 1 Image',
    'name' => 'slider_1_image',
    'aria-label' => '',
    'type' => 'image',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
     'width' => '',
     'class' => '',
     'id' => '',
    ),
    'return_format' => 'url',
    'library' => 'all',
    'min_width' => '',
    'min_height' => '',
    'min_size' => '',
    'max_width' => '',
    'max_height' => '',
    'max_size' => '',
    'mime_types' => '',
    'preview_size' => 'medium',
   ),
   array(
    'key' => 'field_658a554c41c21',
    'label' => 'Slider 2 Image',
    'name' => 'slider_2_image',
    'aria-label' => '',
    'type' => 'image',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
     'width' => '',
     'class' => '',
     'id' => '',
    ),
    'return_format' => 'url',
    'library' => 'all',
    'min_width' => '',
    'min_height' => '',
    'min_size' => '',
    'max_width' => '',
    'max_height' => '',
    'max_size' => '',
    'mime_types' => '',
    'preview_size' => 'medium',
   ),
   array(
    'key' => 'field_658a55641eaee',
    'label' => 'Slider 3 Image',
    'name' => 'slider_3_image',
    'aria-label' => '',
    'type' => 'image',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
     'width' => '',
     'class' => '',
     'id' => '',
    ),
    'return_format' => 'url',
    'library' => 'all',
    'min_width' => '',
    'min_height' => '',
    'min_size' => '',
    'max_width' => '',
    'max_height' => '',
    'max_size' => '',
    'mime_types' => '',
    'preview_size' => 'medium',
   ),
  ),
  'location' => array(
   array(
    array(
     'param' => 'post_type',
     'operator' => '==',
     'value' => 'page',
    ),
   ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => true,
  'description' => '',
  'show_in_rest' => 0,
 ));

 acf_add_local_field_group(array(
  'key' => 'group_658a637435d88',
  'title' => 'Social Profiles',
  'fields' => array(
   array(
    'key' => 'field_658a637466e08',
    'label' => 'Facebook',
    'name' => 'facebook',
    'aria-label' => '',
    'type' => 'text',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
     'width' => '',
     'class' => '',
     'id' => '',
    ),
    'default_value' => '',
    'maxlength' => '',
    'placeholder' => '',
    'prepend' => '',
    'append' => '',
   ),
   array(
    'key' => 'field_658a63de66e09',
    'label' => 'LinkedIn',
    'name' => 'linkedin',
    'aria-label' => '',
    'type' => 'text',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
     'width' => '',
     'class' => '',
     'id' => '',
    ),
    'default_value' => '',
    'maxlength' => '',
    'placeholder' => '',
    'prepend' => '',
    'append' => '',
   ),
   array(
    'key' => 'field_658a63e766e0a',
    'label' => 'Instagram',
    'name' => 'instagram',
    'aria-label' => '',
    'type' => 'text',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
     'width' => '',
     'class' => '',
     'id' => '',
    ),
    'default_value' => '',
    'maxlength' => '',
    'placeholder' => '',
    'prepend' => '',
    'append' => '',
   ),
  ),
  'location' => array(
   array(
    array(
     'param' => 'user_form',
     'operator' => '==',
     'value' => 'all',
    ),
   ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => true,
  'description' => '',
  'show_in_rest' => 0,
 ));
});

